### ISSUE TITLE
评论提交后显示问题，未登录无法点击文章页面详情

### ISSUE THREAD

**Issue by HelloWorldhao** [michaelweixi/blogdemo2#1]
未登录时，是否可查看文章详情，post控制器中ACF应去除。去除后，未登录时，点击文章查看详情会报错。原因未登录时， `Yii::$app->user->id`为空，
提议改为
` $commentModel = new Comment();
   if(Yii::$app->user->id){
       $userMe = User::findOne(Yii::$app->user->id);
       $commentModel->email = $userMe->email
       $commentModel->userid = $userMe->id;
  }`
评论提交后，页面提示尽快审核，但是页面中显示是该文章作者的时间和名称，原因使用了`$model`,应使用`$commentModel`。
一点粗略建议，希望你的作品越来越好。

**Comment by michaelweixi** [comment]
非常感谢，您的建议可以很好的解决存在的问题。我会多收集一些bug，到时统一在V1.18更正。再次感谢。
